### ISSUE TITLE
Update on including chrono-swift in Xcode project

### ISSUE THREAD

**Issue by tsaience** [neilsardesai/chrono-swift#2]
I tried dragging in the folder Chrono, but that didn't compile, so I fixed the issue by including the files *Chrono.swift*, *ChronoParsedResult.swift*, and *chrono.min.js* in my repo. Not sure if others ran into this issue. Currently using Xcode 8.3.2

**Comment by neilsardesai** [comment]
Whoops, I updated the sample app recently using Xcode 9, which is probably why it didn’t compile for you on Xcode 8. Reducing the minimum build target and setting the Swift Language Version in your Build Settings to Swift 3 instead of Swift 4 should fix compiling on Xcode 8.
